Fixes collectd memory extension
This change corrects the variable name that was misspelled
in the collectd memory plugin causing it to fail:

Error message:
Unhandled python exception in read callback: NameError:
 name 'slab' is not defined
Traceback (most recent call last):
  File "/opt/collectd/extensions/python/memory.py",
  line 703, in read_func
    obj.normal_nodes = calc_normal_memory_nodes()
  File "/opt/collectd/extensions/python/memory.py",
  line 354, in calc_normal_memory_nodes
    normal_nodes[node]['slab_MiB'] = slab
NameError: name 'slab' is not defined

Working Logs:
2023-05-18T18:09:59.124 controller-0 collectd[280000]: info
 4K memory usage: Anon: 18.6%, Anon: 4222.6 MiB,
 cgroup-rss: 4271.8 MiB, Avail: 18460.1 MiB,
 Total: 22682.7 MiB Slab: 867.3 MiB
2023-05-18T18:09:59.124 controller-0 collectd[280000]: info
 4K numa memory usage: node0, Anon: 18.15%,
 Anon: 4222.6 MiB, Avail: 19041.8 MiB,
 Total: 23264.4 MiB Slab: 867.3 MiB

Test Plan:
   - PASS: Build an image, install and bootstrap successfully
   - PASS: Apply monitor pods so addon logs would be installed.
   - PASS: Check that log entries are correctly displayed.

Closes-Bug: 2019007

Change-Id: Ic0089fd1c6922fe8ec02e9161f57421f9bb77209
Signed-off-by: cpompeud <Cesar.PompeudeBarrosBombonate@windriver.com>