DEV: Handle per instance holdover and offset values in PTP collectd
This commit enhances the ptp collectd plugin to parse the instance-
monitoring.conf and set per-instance holdover and offset tolerances.
The values in the config file will be set for the appropriate instances.
These per instance config values (holdover_seconds, offset_threshold_
minor_nsec, offset_threshold_minor_nsec) is used to transition from
holdover to freerun and for offset tolerance checking for the minor/
major alarms.

TEST PLAN:
PASS: Add "monitoring" section parameters in one ptpinstance and check
      configured and default values in instance-monitoring.conf and
      validate threshold check
      - system ptp-instance-parameter-add ptpinstance1 --section monitoring
        holdover_seconds=24400 offset_threshold_minor_nsec=2000
        offset_threshold_major_nsec=2000000
      - system ptp-instance-apply
      - check /etc/linuxptp/ptpinstance/instance-monitoring.conf
        [phcinst0]
        holdover_seconds 14400
        offset_threshold_major_nsec 1000000
        offset_threshold_minor_nsec 1000

        [ptpinstance1]
        holdover_seconds 24400
        offset_threshold_major_nsec 2000000
        offset_threshold_minor_nsec 2000

        [ptpinstance2]
        holdover_seconds 14400
        offset_threshold_major_nsec 1000000
        offset_threshold_minor_nsec 1000

      - check /var/log/collectd.log, shows no errors, check for info log
        of monitoring_parameters.
        info ptp plugin PTP instance phcinst0's monitoring_parameters:
            {'holdover_seconds': 14400, 'offset_threshold_major_nsec':
            1000000, 'offset_threshold_minor_nsec': 1000}
        info ptp plugin PTP instance ptpinstance1's monitoring_parameters:
             {'holdover_seconds': 24400, 'offset_threshold_major_nsec':
             2000000, 'offset_threshold_minor_nsec': 2000}
        info ptp plugin PTP instance ptpinstance2's monitoring_parameters:
             {'holdover_seconds': 14400, 'offset_threshold_major_nsec':
             1000000, 'offset_threshold_minor_nsec': 1000}
       - Triggering OOT alarm:
         - "fm alarm-list" shows alarm reason with configured threshold:
           controller-0 Precision Time Protocol (PTP) clocking is out of
           tolerance by more than 10 seconds (configured threshold: minor:
           2000 nsec, major:2000000 nsec)
         - shows collectd info log with configured threshold
            PTP instance: ptpinstance1 ; Skew:67338261885 (configured
            threshold: minor:2000, major:2000000)
 PASS: non integer value for thresholds, takes default values, without crash
       - system ptp-instance-parameter-delete ptpinstance1 --section monitoring
         offset_threshold_minor_nsec=2000
       - system ptp-instance-parameter-add ptpinstance1 --section monitoring
         offset_threshold_minor_nsec=2000xy
       - system ptp-instance-apply
       - check /var/log/collectd.log
          info ptp plugin Reading PTP instance ptpinstance1's parameter
          offset_threshold_minor_nsec value:2000xy from config file
          /etc/linuxptp/ptpinstance/instance-monitoring.conf failed.
          error: invalid literal for int() with base 10: '2000xy'.
          Using default value:1000
          info ptp plugin PTP instance ptpinstance1's monitoring_parameters:
          {'holdover_seconds': 24400, 'offset_threshold_major_nsec': 2000000,
          'offset_threshold_minor_nsec': 1000}
        - Triggering alarm shows configured threshold on reason of "fm alarm-list":
          controller-0 Precision Time Protocol (PTP) clocking is out of tolerance
          by more than 10 seconds (configured threshold: minor:1000 nsec, major:2000000 nsec)

Story: 2011536
Task: 53523

Depends-on: https://review.opendev.org/c/starlingx/config/+/971114

Change-Id: Idf85526ec105e788f618c572abdfe6bdd8927b53
Signed-off-by: Tara Nath Subedi <tara.subedi@windriver.com>